name: Deploy Next.js to AWS

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.EC2_REGION }}

      - name: Build and push Docker image
        run: |
          docker build -t churches_app/web .
          docker tag churchesApp-web:latest ${{ secrets.EC2_ACC_ID }}.dkr.ecr.${{ secrets.EC2_REGION }}.amazonaws.com/${{ secrets.EC2_REPO }}
          docker push ${{ secrets.EC2_ACC_ID }}.dkr.ecr.${{ secrets.EC2_REGION }}.amazonaws.com/${{ secrets.EC2_REPO }}

      - name: SSH to EC2 and deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          # source: "docker-compose.yml"  # Se você estiver usando docker-compose
          target: "/home/ubuntu/churches_app_web/"

      - name: Run Docker Compose
        run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'docker-compose up -d'
