name: Deploy to CapRover

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: "npm"

      - run: npm install  # Instala as dependências

      - run: npm run build  # Gera a build da aplicação Next.js

      - run: ls -la .next  && pwd # Lista os arquivos na pasta .next

      - uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: "./"
          files: |
            .next           # Pasta gerada pela build do Next.js
            public          # Pasta pública
            captain-definition  # Definição do CapRover
          outPath: deploy.tar

      - name: Deploy App to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: '${{ secrets.CAPROVER_SERVER }}'
          app: '${{ secrets.APP_NAME }}'
          token: '${{ secrets.APP_TOKEN }}'
